services:
#    core.example:
#        class: CoreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    admin.category:
        class: AdminBundle\Admin\CategoryAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "app.admin.group.article"
              label: "Category"
              label_catalogue: "CoreBundle"
        arguments:
            - ~
            - CoreBundle\Entity\Category
            - ~
        public: true

    admin.article:
        class: AdminBundle\Admin\ArticleAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "app.admin.group.article"
              label: "Article"
              label_catalogue: "CoreBundle"
        arguments:
            - ~
            - CoreBundle\Entity\Article
            - ~
        public: true
    admin.comment:
        class: AdminBundle\Admin\CommentAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "app.admin.group.article"
              label: "Comment"
              label_catalogue: "CoreBundle"
        arguments:
            - ~
            - CoreBundle\Entity\Comment
            - ~
        public: true