# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        CoreBundle\Entity\AdminUser:
            algorithm: bcrypt
        CoreBundle\Entity\User:
            algorithm: bcrypt
    providers:
        admin_user:
            entity: { class: CoreBundle\Entity\AdminUser, property: username }
        user:
            entity: { class: CoreBundle\Entity\User, property: username }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
